# Generated by Django 3.1.1 on 2020-09-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ad daxil edin', max_length=50, verbose_name='Ad:')),
                ('surname', models.CharField(help_text='Soyad daxil edin', max_length=50, verbose_name='Soyad:')),
                ('email', models.EmailField(help_text='Poçt ünvanını daxil edin', max_length=50, unique=True, verbose_name='Poçt ünvanı:')),
                ('age', models.IntegerField(help_text='Yas daxil edin', verbose_name='Yas:')),
                ('gender', models.IntegerField(choices=[(0, 'Kişi'), (1, 'Qadın')])),
            ],
        ),
    ]
